Fix ValueError #284
k4m4/kickthemout pull request #294
Opened 2018-04-29 20:39 UTC by Urgau

Scapy return a new tuple for routes : (dst_int, msk_int, gw_str, iff, ifaddr, metric), so fix the code.

2018-04-30 10:06 UTC, k4m4 requested changes

2018-04-30 10:06 UTC, k4m4 commented on kickthemout.py
> +    network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
Thank you for your contribution! Let's make this compatible with both old and new versions of scapy:
```
try:
  network, netmask, _, interface, address = max(iface_routes, key=lambda item:item[1])
except:
  network, netmask, _, interface, address, _ = max(iface_routes, key=lambda item:item[1])
```

2018-06-04 11:12 UTC, Urgau commented
Is there anything else to do before merging ?

2018-06-07 21:00 UTC, k4m4 commented
Hi again. I'm just thinking whether this is the best approach to this issue.

2018-09-24 11:57 UTC, Urgau commented
Have you enough thinking ?

2018-10-20 23:32 UTC, BlueArduino20 commented
This works for me, thank you @Urgau

2018-11-07 08:01 UTC, k4m4 commented
The error this PR solves should be resolved in the latest KickThemOut release. Can anyone reproduce? Thanks!

2022-01-30 23:02 UTC, closed without merging